package org.gephi.plugins.example.statistics;

import javax.swing.*;
import java.awt.*;

public class CountSelfLoopPanel extends javax.swing.JPanel{


    public CountSelfLoopPanel() {
        initComponents();
    }

    public void setConnectionsOnly(boolean connectionsOnly) {
        justConnectionsRadio.setSelected(connectionsOnly);
        //allNodesRadio.setSelected(!connectionsOnly);
    }

    public boolean isConnectionsOnly() {
        return justConnectionsRadio.isSelected();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

//        String[] Examples = {
//                "a",
//                "b",
//                "c"
//        };

        button = new javax.swing.JRadioButton[3];

        buttonGroup = new javax.swing.ButtonGroup();
        jXHeader1 = new org.jdesktop.swingx.JXHeader();

        for (int i = 0;i<3;i++) {
            button[i] = new javax.swing.JRadioButton();
            button[i].setMargin(new Insets(5,30,5,5));
        }
        justConnectionsRadio = new javax.swing.JRadioButton();

        label = new javax.swing.JLabel();

        jXHeader1.setDescription("TODO"); // NOI18N
        jXHeader1.setTitle("Graph Embedding"); // NOI18N


        label.setText("Select ...");

        for (int i = 0;i<3;i++) {
            buttonGroup.add(button[i]);
            button[i].setText("Button "+ i); // NOI18N
        }


        buttonGroup.add(justConnectionsRadio);
        justConnectionsRadio.setText("Just connections"); // NOI18N

        //javax.swing.JPanel panel = new javax.swing.JPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        GroupLayout.ParallelGroup prova_H = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);

        GroupLayout.SequentialGroup prova_V = layout.createSequentialGroup();
//        GroupLayout.Group prova1;
        for (JRadioButton i : button){
            prova_H.addComponent(i);
        }
        for (JRadioButton i : button){

            prova_V.addComponent(i);
        }

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jXHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(label)
                                .addContainerGap(354, Short.MAX_VALUE))

                        .addGroup(prova_H)

                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(justConnectionsRadio)
                                .addContainerGap(382, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jXHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label)
                                .addGroup(prova_V)

                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(justConnectionsRadio)
                                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton[] button;
    private javax.swing.ButtonGroup buttonGroup;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    private javax.swing.JRadioButton justConnectionsRadio;
    private javax.swing.JLabel label;

    // End of variables declaration//GEN-END:variables

}
